version: '3'

services:

  schema-registry-cli:
    image:  ttimot24/schema-registry-cli:0.2
    build: .
    environment:
      SCHEMA_REGISTRY_URL: schema-registry:8081
      SCHEMA_TYPE: ".avsc"
    command:  bash -c "/usr/bin/migrate-schemas.sh"
    volumes:
      - ./schemas:/tmp/schemas:ro
